'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import {
  clearCalendarTrainingPlan,
  getTrainingCalendar,
  importPlanToCalendar,
  listTrainingPlans,
  type TrainingCalendarEvent,
  type TrainingCalendarResponse,
  type TrainingEvaluationSummary,
  type TrainingEvaluationResult,
  type TrainingPlanSummary,
} from '@/lib/api';
import {
  T, Btn, Card, PageHero, SectionLabel, Banner, StatusBadge,
} from '@/components/track';

const WEEKDAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function dateOnly(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function parseDate(d: string): Date {
  const [y, m, day] = d.split('-').map(Number);
  return new Date(y, m - 1, day);
}

function addDays(d: Date, days: number): Date {
  const out = new Date(d);
  out.setDate(out.getDate() + days);
  return out;
}

function monthStart(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth(), 1);
}

function monthEnd(d: Date): Date {
  return new Date(d.getFullYear(), d.getMonth() + 1, 0);
}

function monthLabel(d: Date): string {
  return `${d.getFullYear()}year ${d.getMonth() + 1}month`;
}

function monthGrid(d: Date): Array<string | null> {
  const first = monthStart(d);
  const last = monthEnd(d);
  const out: Array<string | null> = Array.from({ length: first.getDay() }, () => null);
  for (let cursor = first; cursor <= last; cursor = addDays(cursor, 1)) {
    out.push(dateOnly(cursor));
  }
  while (out.length % 7 !== 0) out.push(null);
  return out;
}

function formatMD(date: string): string {
  const d = parseDate(date);
  return `${d.getMonth() + 1}/${d.getDate()}`;
}

function sportLabel(sport: string): string {
  if (sport === 'running') return 'Running';
  if (sport === 'cycling') return 'Cycling';
  if (sport === 'swimming') return 'Swimming';
  if (sport === 'rest') return 'Rest';
  if (sport === 'strength') return 'Strength';
  if (sport === 'mobility') return 'Recovery';
  return 'Sport';
}

function regionLabel(region: string | null): string {
  if (region === 'cn') return 'CN';
  if (region === 'global') return 'International';
  return 'Garmin';
}

function metricText(e: TrainingCalendarEvent): string[] {
  const out: string[] = [];
  if (e.distanceKm != null && e.distanceKm > 0) out.push(`${Number(e.distanceKm).toFixed(1)}km`);
  if (e.durationMinutes != null && e.durationMinutes > 0) out.push(`${e.durationMinutes}min`);
  if (e.kind === 'garmin_activity') {
    const avgHr = e.metrics.averageHr;
    const load = e.metrics.trainingLoad;
    const power = e.metrics.averagePower;
    if (typeof avgHr === 'number') out.push(`${Math.round(avgHr)}bpm`);
    if (typeof power === 'number') out.push(`${Math.round(power)}W`);
    if (typeof load === 'number') out.push(`Load ${Math.round(load)}`);
    return out;
  }
  if (e.targetPower && e.targetPower !== 'N/A') out.push(e.targetPower);
  else if (e.targetHeartRate && e.targetHeartRate !== 'N/A') out.push(e.targetHeartRate);
  else if (e.targetPace && e.targetPace !== 'N/A') out.push(e.targetPace);
  return out;
}

function eventAccent(e: TrainingCalendarEvent): string {
  if (e.kind === 'garmin_activity') return T.cyan;
  if (e.intensity === 'high') return T.red;
  if (e.intensity === 'medium') return T.amber;
  return T.lime;
}

function formatWeekStart(d: string): string {
  const date = parseDate(d);
  return `${date.getMonth() + 1}/${date.getDate()} ${WEEKDAYS[date.getDay()]}`;
}

function eventTime(e: TrainingCalendarEvent): string | null {
  if (!e.startTimeLocal) return null;
  return new Date(e.startTimeLocal).toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
  });
}

export default function CalendarPage() {
  const [data, setData] = useState<TrainingCalendarResponse | null>(null);
  const [plans, setPlans] = useState<TrainingPlanSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [busyPlanId, setBusyPlanId] = useState<string | null>(null);
  // evaluationBusy and selectedActivityKeys removed — evaluations are now auto-generated by the backend
  const today = useMemo(() => {
    const d = new Date();
    d.setHours(0, 0, 0, 0);
    return d;
  }, []);
  const range = useMemo(() => ({
    from: dateOnly(addDays(today, -30)),
    to: dateOnly(addDays(today, 30)),
  }), [today]);
  const [visibleMonth, setVisibleMonth] = useState(monthStart(today));
  const [selectedDate, setSelectedDate] = useState(dateOnly(today));

  async function refresh() {
    setLoading(true);
    setError(null);
    try {
      const [calendarRes, plansRes] = await Promise.all([
        getTrainingCalendar(range),
        listTrainingPlans(),
      ]);
      setData(calendarRes);
      setPlans(plansRes.plans.filter((p) => p.status === 'ready'));
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { refresh(); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    setNotice(null);
  }, [selectedDate]);

  const eventsByDate = useMemo(() => {
    const m = new Map<string, TrainingCalendarEvent[]>();
    for (const e of data?.events ?? []) {
      const list = m.get(e.date) ?? [];
      list.push(e);
      m.set(e.date, list);
    }
    return m;
  }, [data]);

  const evaluationsByDate = useMemo(() => {
    const m = new Map<string, TrainingEvaluationSummary[]>();
    for (const e of data?.evaluations ?? []) {
      const list = m.get(e.date) ?? [];
      list.push(e);
      m.set(e.date, list);
    }
    return m;
  }, [data]);

  const selectedEvents = eventsByDate.get(selectedDate) ?? [];
  const selectedPlanEvents = selectedEvents.filter((e) => e.kind === 'planned_workout');
  const selectedActivityEvents = selectedEvents.filter((e) => e.kind === 'garmin_activity');
  const selectedEvaluations = evaluationsByDate.get(selectedDate) ?? [];
  const activitySourceErrors = (data?.calendar.activitySources ?? []).filter((source) => source.error);
  const gridDays = monthGrid(visibleMonth);
  const prevMonth = monthStart(new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() - 1, 1));
  const nextMonth = monthStart(new Date(visibleMonth.getFullYear(), visibleMonth.getMonth() + 1, 1));
  const canPrev = dateOnly(monthEnd(prevMonth)) >= range.from;
  const canNext = dateOnly(nextMonth) <= range.to;

  async function clearActivePlan() {
    if (!window.confirm('ConfirmRemove the current training plan from the calendar?')) return;
    try {
      await clearCalendarTrainingPlan();
      setNotice('The current calendar plan was removed.');
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    }
  }

  async function applyPlan(plan: TrainingPlanSummary) {
    const ok = window.confirm('ConfirmApply this training plan to the calendar? It will repeat the 7-day schedule for the next 30 days and replace the current plan.');
    if (!ok) return;
    setBusyPlanId(plan.id);
    setError(null);
    setNotice(null);
    try {
      await importPlanToCalendar(plan.id);
      setNotice('Applied to the calendar for the next 30 days.');
      await refresh();
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusyPlanId(null);
    }
  }

  return (
    <>
      <PageHero
        eyebrow="Personal calendar"
        title="TrainingCalendar"
        sub={`${range.from} to ${range.to} · onetimesView onemonth`}
        actions={
          <>
            {data?.calendar.activePlan ? (
              <>
                <StatusBadge kind="ready" />
                <Link href={`/training/${data.calendar.activePlan.id}`} style={{ textDecoration: 'none' }}>
                  <Btn variant="ghost" size="sm">Current plan</Btn>
                </Link>
                <Btn variant="ghost" size="sm" onClick={clearActivePlan}>Remove plan</Btn>
              </>
            ) : (
              <Link href="/training/new" style={{ textDecoration: 'none' }}>
                <Btn variant="ghost" size="sm">New plan</Btn>
              </Link>
            )}
          </>
        }
      />

      {error && <div style={{ marginBottom: 18 }}><Banner kind="error" code="ERR">{error}</Banner></div>}
      {notice && <div style={{ marginBottom: 18 }}><Banner kind="ok" code="OK">{notice}</Banner></div>}
      {activitySourceErrors.length > 0 && (
        <div style={{ marginBottom: 18 }}>
          <Banner kind="warn" code="GARMIN">
            {activitySourceErrors
              .map((source) => `${regionLabel(source.region)}activityRead failed. Please reconnect Garmin.`)
              .join('；')}
          </Banner>
        </div>
      )}

      {loading && (
        <div style={{ fontFamily: T.mono, fontSize: 12, color: T.inkFaint, letterSpacing: 1.5 }} className="track-blink">
          // Loading calendar…
        </div>
      )}

      {!loading && (
        <>
          <SectionLabel>Apply training plan</SectionLabel>
          <Card style={{ padding: 16, marginBottom: 22 }}>
            {plans.length === 0 ? (
              <div style={{ color: T.inkFaint, fontSize: 13 }}>No plan is available to apply.</div>
            ) : (
              <div style={{ display: 'grid', gap: 10 }}>
                {plans.map((p) => {
                  const active = data?.calendar.activePlanId === p.id;
                  return (
                    <div
                      key={p.id}
                      style={{
                        display: 'grid',
                        gridTemplateColumns: 'minmax(0, 1fr) auto',
                        alignItems: 'center',
                        gap: 12,
                        border: `1px solid ${active ? T.lime : T.border}`,
                        borderRadius: 8,
                        padding: 12,
                        background: active ? 'rgba(198,255,58,0.04)' : 'rgba(255,255,255,0.02)',
                      }}
                    >
                      <div style={{ minWidth: 0 }}>
                        <div style={{ fontFamily: T.mono, fontSize: 10, color: active ? T.lime : T.inkFaint, letterSpacing: 1.2, marginBottom: 4 }}>
                          {formatWeekStart(p.weekStartDate)} · 30-day loop
                        </div>
                        <div style={{ color: T.ink, fontSize: 14, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                          {p.summary ?? 'Trainingplan'}
                        </div>
                      </div>
                      <Btn
                        variant={active ? 'ok' : 'ghost'}
                        size="sm"
                        onClick={() => applyPlan(p)}
                        disabled={active || busyPlanId === p.id}
                      >
                        {active ? 'Applied' : busyPlanId === p.id ? 'Applying…' : 'Apply for the next 30 days'}
                      </Btn>
                    </div>
                  );
                })}
              </div>
            )}
          </Card>

          <SectionLabel
            right={
              <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
                <Btn variant="ghost" size="sm" onClick={() => setVisibleMonth(prevMonth)} disabled={!canPrev}>Previous month</Btn>
                <div style={{ fontFamily: T.mono, fontSize: 12, color: T.ink }}>{monthLabel(visibleMonth)}</div>
                <Btn variant="ghost" size="sm" onClick={() => setVisibleMonth(nextMonth)} disabled={!canNext}>Next month</Btn>
              </div>
            }
          >
            Month view
          </SectionLabel>
          <div style={{ overflowX: 'auto', marginBottom: 24, paddingBottom: 6 }}>
            <div style={{ minWidth: 980 }}>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(7, minmax(132px, 1fr))', gap: 10, marginBottom: 10 }}>
                {WEEKDAYS.map((day) => (
                  <div key={day} style={{ fontFamily: T.mono, fontSize: 10, color: T.inkFaint, letterSpacing: 1.2, padding: '0 4px' }}>
                    {day}
                  </div>
                ))}
              </div>
              <div
                style={{
                  display: 'grid',
                  gridTemplateColumns: 'repeat(7, minmax(132px, 1fr))',
                  gap: 10,
                }}
              >
                {gridDays.map((day, i) => {
                  if (!day) {
                    return <div key={`blank-${i}`} style={{ minHeight: 172 }} />;
                  }
                  const d = parseDate(day);
                  const isToday = day === dateOnly(today);
                  const selected = day === selectedDate;
                  const inRange = day >= range.from && day <= range.to;
                  const list = eventsByDate.get(day) ?? [];
                  const plannedCount = list.filter((e) => e.kind === 'planned_workout').length;
                  const activityCount = list.filter((e) => e.kind === 'garmin_activity').length;
                  const hasEvaluation = (evaluationsByDate.get(day) ?? []).length > 0;
                  return (
                    <button
                      key={day}
                      type="button"
                      onClick={() => inRange && setSelectedDate(day)}
                      disabled={!inRange}
                      style={{
                        all: 'unset',
                        boxSizing: 'border-box',
                        minHeight: 172,
                        padding: 12,
                        borderRadius: 8,
                        border: `1px solid ${selected ? T.lime : isToday ? T.cyan : T.border}`,
                        background: selected ? 'rgba(198,255,58,0.06)' : 'rgba(255,255,255,0.02)',
                        cursor: inRange ? 'pointer' : 'not-allowed',
                        display: 'flex',
                        flexDirection: 'column',
                        gap: 8,
                        opacity: inRange ? 1 : 0.32,
                      }}
                    >
                      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 6, alignItems: 'baseline' }}>
                        <span style={{ fontFamily: T.mono, fontSize: 11, color: selected ? T.lime : T.inkFaint, letterSpacing: 1.1 }}>
                          {formatMD(day)}
                        </span>
                        <span style={{ fontFamily: T.mono, fontSize: 10, color: isToday ? T.cyan : T.inkFaint }}>
                          {WEEKDAYS[d.getDay()]}
                        </span>
                      </div>
                      <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>
                        {plannedCount > 0 && <MiniBadge color={T.lime}>plan {plannedCount}</MiniBadge>}
                        {activityCount > 0 && <MiniBadge color={T.cyan}>Records {activityCount}</MiniBadge>}
                        {hasEvaluation && <MiniBadge color={T.amber}>Review</MiniBadge>}
                      </div>
                      <div style={{ display: 'grid', gap: 6 }}>
                        {list.slice(0, 4).map((e) => (
                          <div
                            key={e.id}
                            style={{
                              borderLeft: `2px solid ${eventAccent(e)}`,
                              paddingLeft: 7,
                              minWidth: 0,
                            }}
                          >
                            <div style={{ fontSize: 11, color: T.ink, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {e.kind === 'garmin_activity' ? 'Records' : e.sessionLabel ?? 'plan'} · {e.title}
                            </div>
                            <div style={{ fontFamily: T.mono, fontSize: 9, color: T.inkFaint, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                              {metricText(e).slice(0, 2).join(' · ')}
                            </div>
                          </div>
                        ))}
                        {list.length > 4 && (
                          <div style={{ fontFamily: T.mono, fontSize: 9, color: T.inkFaint }}>
                            +{list.length - 4}
                          </div>
                        )}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>

          <SectionLabel>{selectedDate} TrainingDetails</SectionLabel>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(min(320px, 100%), 1fr))', gap: 14, marginBottom: 24 }}>
            <div style={{ display: 'grid', gap: 10 }}>
              {selectedPlanEvents.length === 0 ? (
                <Card style={{ padding: 24, color: T.inkFaint, fontSize: 13, textAlign: 'center' }}>
                  This onedaysNo planTraining。
                </Card>
              ) : (
                selectedPlanEvents.map((e) => <EventDetail key={e.id} event={e} />)
              )}
            </div>
            <div style={{ display: 'grid', gap: 10 }}>
              {selectedActivityEvents.length === 0 ? (
                <Card style={{ padding: 24, color: T.inkFaint, fontSize: 13, textAlign: 'center' }}>
                  This onedaysNo  Garmin activities。
                </Card>
              ) : (
                <Card style={{ padding: 18 }}>
                  <div style={{ fontFamily: T.mono, fontSize: 10, color: T.cyan, letterSpacing: 1.3, marginBottom: 10 }}>
                    GARMIN.ACTIVITIES
                  </div>
                  <div style={{ display: 'grid', gap: 8 }}>
                    {selectedActivityEvents.map((event) => (
                      <ActivityReadOnlyRow key={event.id} event={event} />
                    ))}
                  </div>
                </Card>
              )}
            </div>
          </div>

          {/* Evaluations — auto-generated by the backend */}
          {selectedEvaluations.length > 0 && (
            <>
              <SectionLabel>{selectedDate} TrainingReview</SectionLabel>
              <div style={{ display: 'grid', gap: 10, marginBottom: 24 }}>
                {selectedEvaluations.map((evaluation) => (
                  <EvaluationResultCard key={evaluation.id} evaluation={evaluation} />
                ))}
              </div>
            </>
          )}
        </>
      )}
    </>
  );
}

const VERDICT_ZH: Record<string, { label: string; color: string }> = {
  matched: { label: 'Trainingmatched', color: T.lime },
  under_done: { label: 'Traininginsufficient', color: T.amber },
  over_done: { label: 'Trainingtoo much', color: T.amber },
  different_sport: { label: 'Sportmatch', color: T.cyan },
  missed: { label: 'Trainingmissing', color: T.red },
  rest_day_active: { label: 'Restdaily activity', color: T.cyan },
};

function scoreColor(score: number): string {
  if (score >= 70) return T.lime;
  if (score >= 40) return T.amber;
  return T.red;
}

function ratioText(ratio: number | null | undefined): string {
  if (ratio == null) return '—';
  return `${Math.round(ratio * 100)}%`;
}

function EvaluationResultCard({ evaluation }: { evaluation: TrainingEvaluationSummary }) {
  const ready = evaluation.status === 'ready';
  const statusColor = ready ? T.lime : evaluation.status === 'failed' ? T.red : T.amber;
  const result = evaluation.result;
  const isRich = result != null && result.score !== undefined;

  if (!isRich) {
    return (
      <div
        style={{
          border: `1px solid ${statusColor}40`,
          borderRadius: 8,
          padding: 12,
          background: ready ? T.limeGlow : evaluation.status === 'failed' ? T.redSoft : T.amberSoft,
        }}
      >
        <div style={{ fontFamily: T.mono, fontSize: 10, color: statusColor, letterSpacing: 1.2, marginBottom: 6 }}>
          EVALUATION.{evaluation.status.toUpperCase()}
        </div>
        <div style={{ color: T.ink, fontSize: 13, fontWeight: 700, marginBottom: 6 }}>
          {result?.title ?? 'TrainingReview'}
        </div>
        <div style={{ color: T.inkDim, fontSize: 12, lineHeight: 1.6 }}>
          {result?.summary ?? 'Review submitted. Waiting for generation.'}
        </div>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginTop: 10 }}>
          <MiniBadge color={T.lime}>plan {result?.plannedWorkoutCount ?? evaluation.plannedWorkoutIds.length}</MiniBadge>
          <MiniBadge color={T.cyan}>Sport {result?.activityCount ?? evaluation.activityRefs.length}</MiniBadge>
        </div>
      </div>
    );
  }

  const r = result as TrainingEvaluationResult;
  const sc = r.score ?? 0;
  const sColor = scoreColor(sc);
  const v = r.verdict ? VERDICT_ZH[r.verdict] : null;

  return (
    <div
      style={{
        border: `1px solid ${sColor}40`,
        borderRadius: 8,
        padding: 14,
        background: sc >= 70 ? T.limeGlow : sc >= 40 ? T.amberSoft : T.redSoft,
        display: 'flex',
        flexDirection: 'column',
        gap: 10,
      }}
    >
      {/* Header: score + verdict */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          width: 40, height: 40, borderRadius: '50%',
          border: `2px solid ${sColor}`,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          fontFamily: T.mono, fontSize: 14, fontWeight: 800, color: sColor,
        }}>
          {sc}
        </div>
        <div style={{ flex: 1 }}>
          <div style={{ color: T.ink, fontSize: 14, fontWeight: 700 }}>
            {r.title}
          </div>
          {v && (
            <span style={{
              fontFamily: T.mono, fontSize: 9, color: v.color,
              border: `1px solid ${v.color}40`, borderRadius: 4,
              padding: '1px 5px', marginTop: 2, display: 'inline-block',
            }}>
              {v.label}
            </span>
          )}
        </div>
      </div>

      {/* Summary */}
      <div style={{ color: T.inkDim, fontSize: 12, lineHeight: 1.6 }}>
        {r.summary}
      </div>

      {/* Adherence grid */}
      {r.adherence && (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 6 }}>
          <MiniStat label="Sport match" value={r.adherence.sportMatched ? '✓' : '✗'} color={r.adherence.sportMatched ? T.lime : T.red} />
          <MiniStat label="Duration" value={ratioText(r.adherence.durationRatio)} color={ratioStatColor(r.adherence.durationRatio)} />
          <MiniStat label="Distance" value={ratioText(r.adherence.distanceRatio)} color={ratioStatColor(r.adherence.distanceRatio)} />
          <MiniStat label="intensity" value={r.adherence.intensityMatched == null ? '—' : r.adherence.intensityMatched ? '✓' : '✗'} color={r.adherence.intensityMatched ? T.lime : r.adherence.intensityMatched === false ? T.amber : T.inkFaint} />
        </div>
      )}

      {/* Load */}
      {r.load && r.load.comment && (
        <div style={{ fontFamily: T.mono, fontSize: 10, color: T.inkDim }}>
          ⚡ {r.load.comment}
        </div>
      )}

      {/* Physiology metrics */}
      {r.physiology && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, padding: '6px 0' }}>
          {r.physiology.edwardsTRIMP != null && (
            <MiniBadge color={T.cyan}>TRIMP {r.physiology.edwardsTRIMP}</MiniBadge>
          )}
          {r.physiology.garminLoad != null && (
            <MiniBadge color={T.cyan}>Load {r.physiology.garminLoad}</MiniBadge>
          )}
          {r.physiology.hrZone != null && (
            <MiniBadge color={r.physiology.zoneMatch ? T.lime : T.amber}>Zone {r.physiology.hrZone}</MiniBadge>
          )}
          {r.physiology.aerobicTE != null && (
            <MiniBadge color={T.cyan}>AerTE {r.physiology.aerobicTE.toFixed(1)}</MiniBadge>
          )}
          {r.physiology.anaerobicTE != null && r.physiology.anaerobicTE > 0 && (
            <MiniBadge color={T.amber}>AnaTE {r.physiology.anaerobicTE.toFixed(1)}</MiniBadge>
          )}
          {r.physiology.tss != null && (
            <MiniBadge color={T.cyan}>TSS {r.physiology.tss}</MiniBadge>
          )}
          {r.physiology.intensityFactor != null && (
            <MiniBadge color={T.cyan}>IF {r.physiology.intensityFactor.toFixed(2)}</MiniBadge>
          )}
        </div>
      )}

      {/* Highlights / Risks / Suggestions */}
      {r.highlights && r.highlights.length > 0 && (
        <BulletList items={r.highlights} color={T.lime} />
      )}
      {r.risks && r.risks.length > 0 && (
        <BulletList items={r.risks} color={T.red} />
      )}
      {r.suggestions && r.suggestions.length > 0 && (
        <BulletList items={r.suggestions} color={T.amber} />
      )}

      {/* Counts */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
        <MiniBadge color={T.lime}>plan {r.plannedWorkoutCount}</MiniBadge>
        <MiniBadge color={T.cyan}>Sport {r.activityCount}</MiniBadge>
      </div>
    </div>
  );
}

function MiniStat({ label, value, color }: { label: string; value: string; color: string }) {
  return (
    <div style={{ textAlign: 'center' }}>
      <div style={{ fontFamily: T.mono, fontSize: 14, fontWeight: 700, color }}>{value}</div>
      <div style={{ fontSize: 9, color: T.inkFaint, marginTop: 2 }}>{label}</div>
    </div>
  );
}

function ratioStatColor(ratio: number | null | undefined): string {
  if (ratio == null) return T.inkFaint;
  if (ratio >= 0.75 && ratio <= 1.25) return T.lime;
  if (ratio >= 0.5 && ratio <= 1.5) return T.amber;
  return T.red;
}

function BulletList({ items, color }: { items: string[]; color: string }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      {items.map((item, i) => (
        <div key={i} style={{ fontSize: 11, color: T.inkDim, lineHeight: 1.5 }}>
          <span style={{ color, marginRight: 4 }}>●</span>
          {item}
        </div>
      ))}
    </div>
  );
}

function MiniBadge({ color, children }: { color: string; children: ReactNode }) {
  return (
    <span style={{
      fontFamily: T.mono,
      fontSize: 9,
      color,
      border: `1px solid ${color}40`,
      borderRadius: 4,
      padding: '2px 5px',
      background: 'rgba(255,255,255,0.03)',
      whiteSpace: 'nowrap',
    }}>
      {children}
    </span>
  );
}

function ActivityReadOnlyRow({ event }: { event: TrainingCalendarEvent }) {
  const metrics = metricText(event);
  return (
    <div
      style={{
        border: `1px solid ${T.border}`,
        borderRadius: 8,
        padding: 10,
        background: 'rgba(255,255,255,0.02)',
      }}
    >
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 8, marginBottom: 4 }}>
        <div style={{ color: T.ink, fontSize: 13, fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {event.title}
        </div>
        <div style={{ fontFamily: T.mono, fontSize: 10, color: T.cyan, whiteSpace: 'nowrap' }}>
          {eventTime(event) ?? regionLabel(event.region)}
        </div>
      </div>
      <div style={{ fontFamily: T.mono, fontSize: 10, color: T.inkFaint }}>
        {regionLabel(event.region)} · {sportLabel(event.sport)}{metrics.length ? ` · ${metrics.join(' · ')}` : ''}
      </div>
    </div>
  );
}

function EventDetail({ event }: { event: TrainingCalendarEvent }) {
  const metrics = metricText(event);
  return (
    <Card style={{ padding: 18, borderColor: `${eventAccent(event)}60` }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, alignItems: 'flex-start', marginBottom: 10 }}>
        <div style={{ minWidth: 0 }}>
          <div style={{ fontFamily: T.mono, fontSize: 10, color: eventAccent(event), letterSpacing: 1.3, marginBottom: 5 }}>
            PLAN · {sportLabel(event.sport)}
          </div>
          <h2 style={{ margin: 0, color: T.ink, fontSize: 18, fontWeight: 700 }}>
            {event.title}
          </h2>
        </div>
        {event.planId && (
          <Link href={`/training/${event.planId}`} style={{ textDecoration: 'none' }}>
            <Btn variant="ghost" size="sm">Plan details</Btn>
          </Link>
        )}
      </div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: event.workoutStructure || event.targets?.length ? 12 : 0 }}>
        {metrics.map((m) => (
          <span key={m} style={{ fontFamily: T.mono, fontSize: 11, color: T.inkDim, border: `1px solid ${T.border}`, borderRadius: 4, padding: '4px 7px' }}>
            {m}
          </span>
        ))}
      </div>
      {event.workoutStructure && (
        <p style={{ margin: '0 0 10px', color: T.ink, fontSize: 13, lineHeight: 1.7, whiteSpace: 'pre-line' }}>
          {event.workoutStructure}
        </p>
      )}
      {event.targets && event.targets.length > 0 && (
        <div style={{ display: 'grid', gap: 5 }}>
          {event.targets.map((t) => (
            <div key={t} style={{ fontFamily: T.mono, fontSize: 11, color: T.inkDim }}>
              {t}
            </div>
          ))}
        </div>
      )}
    </Card>
  );
}
